version: '3.8'

services:
  chirpy:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - PLATFORM=${PLATFORM:-DEV}
    depends_on:
      - db
    volumes:
      - ./.env:/root/.env

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chirpy
      MYSQL_USER: chirpy_user
      MYSQL_PASSWORD: chirpy_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/schema:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
